### ISSUE TITLE
description on age groups

### ISSUE THREAD

**Issue by dbuijs** [hres/cvapps#103] opened 2016-11-24 18:04 UTC
Under the ''Patients'' tab: It would be useful to have a small description for age groups under the graph or beside the different age groups. For example: Elderly = 65 years old and up.

**Comment by aruu** [comment] 2016-12-02 17:55
fixed in f026cd8, see tooltips

**Comment by aruu** [comment] 2016-12-02 17:56
was a dupe of #12

**Closed as completed by aruu** 2016-12-02 17:56 UTC
Labels: duplicate, resolved, CV, Mandatory
