### ISSUE TITLE
title of report

### ISSUE THREAD

**Issue by dbuijs** [hres/cvapps#102] opened 2016-11-24 18:04 UTC
Under all tabs: It would be useful to have a title that includes the Drug and AE. For example, this is what appears now: Drug Adverse Event Reports for ZYPREXA (34 reports).  It would be useful to have something like: Drug Adverse Event Reports for ZYPREXA and Abdominal pain (34 reports).

**Comment by aruu** [comment] 2016-12-02 17:06
dupe of #30, resolved

**Closed as completed by aruu** 2016-12-02 17:06 UTC
Labels: duplicate, resolved
